-- SignalDesk core schema.
-- Enum-like columns are stored as VARCHAR and mapped with @Enumerated(STRING) in JPA,
-- so adding a new value never requires a DB migration.

-- Actors we track: funds (13F), corporate insiders (Form 4), members of Congress, eToro traders.
CREATE TABLE tracked_actor (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    type        VARCHAR(32)  NOT NULL,   -- FUND | INSIDER | CONGRESS | ETORO
    external_id VARCHAR(128),            -- SEC CIK, congress slug, etc.
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_actor_type_external UNIQUE (type, external_id)
);

-- The normalized shape every source collapses into.
CREATE TABLE trade_signal (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source         VARCHAR(32)  NOT NULL,   -- INSIDER_FORM4 | CONGRESS | ETORO | THIRTEEN_F | OPTIONS_FLOW | ANALYST_RATING
    ticker         VARCHAR(16)  NOT NULL,
    side           VARCHAR(8)   NOT NULL,   -- BUY | SELL | HOLD
    actor_id       BIGINT       REFERENCES tracked_actor (id),
    actor_name     VARCHAR(255),
    transacted_at  DATE,                    -- when the trade actually happened (may be delayed)
    disclosed_at   TIMESTAMPTZ,             -- when it became public
    confidence     NUMERIC(4,3),            -- 0.000 - 1.000, optional
    raw_ref        VARCHAR(255),            -- accession no / external id, for dedup
    created_at     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_signal_source_ref UNIQUE (source, raw_ref)
);
CREATE INDEX idx_signal_ticker      ON trade_signal (ticker);
CREATE INDEX idx_signal_disclosed   ON trade_signal (disclosed_at DESC);

-- Validation inputs the AI weighs against signals: analyst ratings, earnings, 8-K, technicals.
CREATE TABLE context_event (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker     VARCHAR(16)  NOT NULL,
    type       VARCHAR(32)  NOT NULL,   -- ANALYST_RATING | EARNINGS | EIGHT_K | TECHNICAL | FUNDAMENTAL
    summary    TEXT,
    payload    JSONB,                   -- raw structured detail
    event_at   TIMESTAMPTZ,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_context_ticker ON context_event (ticker);
CREATE INDEX idx_context_event_at ON context_event (event_at DESC);

CREATE TABLE news_item (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker       VARCHAR(16),
    headline     TEXT         NOT NULL,
    url          VARCHAR(1024),
    source       VARCHAR(128),
    published_at TIMESTAMPTZ,
    sentiment    NUMERIC(4,3),           -- -1.000 .. 1.000
    created_at   TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_news_url UNIQUE (url)
);
CREATE INDEX idx_news_ticker ON news_item (ticker);
CREATE INDEX idx_news_published ON news_item (published_at DESC);

-- Claude's stored daily research output (ticker null = a global market briefing).
CREATE TABLE briefing (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    briefing_date DATE         NOT NULL,
    ticker        VARCHAR(16),
    signal        VARCHAR(8),             -- BUY | SELL | HOLD | null
    confidence    NUMERIC(4,3),
    summary       TEXT         NOT NULL,
    model         VARCHAR(64),
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_briefing_date ON briefing (briefing_date DESC);

-- Alerts pushed to LINE. sent_at null = generated but not yet delivered.
CREATE TABLE alert (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker      VARCHAR(16)  NOT NULL,
    signal      VARCHAR(8)   NOT NULL,
    confidence  NUMERIC(4,3),
    reason      TEXT,
    briefing_id BIGINT       REFERENCES briefing (id),
    sent_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_alert_ticker ON alert (ticker);

-- Your paper portfolio, synced from Alpaca (or manually entered).
CREATE TABLE portfolio_position (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker       VARCHAR(16)   NOT NULL,
    shares       NUMERIC(18,4) NOT NULL,
    cost_basis   NUMERIC(18,4),
    market_value NUMERIC(18,4),
    source       VARCHAR(16)   NOT NULL DEFAULT 'ALPACA',  -- ALPACA | MANUAL
    updated_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_position_source_ticker UNIQUE (source, ticker)
);
