-- Companies whose insider (Form 4) activity we watch. CIK is 10-digit zero-padded
-- so it drops straight into the SEC submissions URL.
CREATE TABLE tracked_issuer (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticker     VARCHAR(16)  NOT NULL,
    cik        VARCHAR(10)  NOT NULL,
    name       VARCHAR(255) NOT NULL,
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_issuer_cik UNIQUE (cik),
    CONSTRAINT uq_issuer_ticker UNIQUE (ticker)
);

INSERT INTO tracked_issuer (ticker, cik, name) VALUES
    ('AAPL', '0000320193', 'Apple Inc.'),
    ('MSFT', '0000789019', 'Microsoft Corporation'),
    ('NVDA', '0001045810', 'NVIDIA Corporation'),
    ('TSLA', '0001318605', 'Tesla, Inc.'),
    ('AMZN', '0001018724', 'Amazon.com, Inc.'),
    ('META', '0001326801', 'Meta Platforms, Inc.')
ON CONFLICT (cik) DO NOTHING;
