-- 13F holdings per fund per filing period. Same CUSIP is aggregated to one row per filing.
CREATE TABLE fund_holding (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor_id          BIGINT       NOT NULL REFERENCES tracked_actor (id),
    cik               VARCHAR(10)  NOT NULL,
    accession         VARCHAR(32)  NOT NULL,
    period_of_report  DATE         NOT NULL,
    filed_at          DATE,
    cusip             VARCHAR(16)  NOT NULL,
    issuer_name       VARCHAR(255),
    ticker            VARCHAR(16),                 -- resolved lazily via OpenFIGI (may be null)
    shares            NUMERIC(24,4),
    value             NUMERIC(24,2),               -- reported value in USD
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_holding_accession_cusip UNIQUE (accession, cusip)
);
CREATE INDEX idx_holding_actor_period ON fund_holding (actor_id, period_of_report DESC);

-- Cache of CUSIP -> ticker lookups so we don't re-hit OpenFIGI. ticker null = looked up, not found.
CREATE TABLE cusip_ticker (
    cusip      VARCHAR(16) PRIMARY KEY,
    ticker     VARCHAR(16),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
