-- Per-horizon backtest scoring. Each directional (BUY/SELL) horizon of a briefing gets its own score
-- row, evaluated once its own window has passed (short ~5d, swing ~15d, long ~60d) — so a long-term
-- call is judged on months, not a week. entry_price stays on `briefing` (shared entry at creation) and
-- is copied onto the score row so scoring is self-contained.

-- The old single-horizon result columns (from V6) are replaced by this table. entry_price is kept.
DROP INDEX IF EXISTS idx_briefing_evaluated;
ALTER TABLE briefing DROP COLUMN IF EXISTS horizon_days;
ALTER TABLE briefing DROP COLUMN IF EXISTS evaluated_at;
ALTER TABLE briefing DROP COLUMN IF EXISTS exit_price;
ALTER TABLE briefing DROP COLUMN IF EXISTS return_pct;
ALTER TABLE briefing DROP COLUMN IF EXISTS correct;

CREATE TABLE briefing_score (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    briefing_id  BIGINT        NOT NULL REFERENCES briefing(id) ON DELETE CASCADE,
    ticker       VARCHAR(16)   NOT NULL,
    horizon      VARCHAR(8)    NOT NULL,          -- SHORT | SWING | LONG
    signal       VARCHAR(8)    NOT NULL,          -- BUY | SELL
    horizon_days INT           NOT NULL,
    entry_price  NUMERIC(18,4) NOT NULL,
    due_date     DATE          NOT NULL,          -- briefing_date + horizon_days; when it becomes scorable
    exit_price   NUMERIC(18,4),
    return_pct   NUMERIC(10,3),
    correct      BOOLEAN,
    evaluated_at TIMESTAMPTZ,
    created_at   TIMESTAMPTZ   NOT NULL DEFAULT now(),
    CONSTRAINT uq_briefing_score UNIQUE (briefing_id, horizon)
);

-- The evaluator scans for pending rows that are due.
CREATE INDEX idx_score_pending ON briefing_score (evaluated_at, due_date);
